FROM node:11.1.0

RUN apt-get update && \
    apt-get install -y imagemagick graphicsmagick && \
    apt-get clean

WORKDIR /project

ADD ./package.json ./
RUN npm install

ADD ./gulpfile.js ./

ENTRYPOINT "$(npm bin)/gulp"
